/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package p1;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String getVersion(){
        Properties prop = new Properties();

        InputStream x = getClass().getClassLoader().getResourceAsStream("version.txt");
        try {
            prop.load(x);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return (String)prop.get("version");
    }
    public static void main(String[] args) {
        App app = new App();
        System.out.println("Greeting = " + app.getGreeting());
        System.out.println("Version = " + app.getVersion());
    }
}
